openapi: 3.0.3
info:
  title: Управление коллекцией SpaceMarine
  description: API для управления коллекцией SpaceMarine
  version: 1.0.0
  contact:
    name: Ваше имя
  license:
    name: Лицензия
servers:
  - url: http://localhost:4532/api/v1
paths:
  /api/v1/space-marines:
    get:
      summary: Получить список SpaceMarine
      operationId: getSpaceMarines
      parameters:
        - name: page
          in: query
          description: Номер страницы (по умолчанию 1)
          required: false
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          description: Размер страницы (по умолчанию 10)
          required: false
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          description: Поле для сортировки (например, "name")
          required: false
          schema:
            type: string
        - name: order
          in: query
          description: Порядок сортировки (asc или desc)
          required: false
          schema:
            type: string
            enum:
              - asc
              - desc
        - name: name
          in: query
          description: Фильтр по имени
          required: false
          schema:
            type: string
        - name: coordinatesX
          in: query
          description: Фильтр по координате X
          required: false
          schema:
            type: integer
        - name: coordinatesY
          in: query
          description: Фильтр по координате Y
          required: false
          schema:
            type: integer
        - name: loyal
          in: query
          description: Фильтр по полю loyal (true/false)
          required: false
          schema:
            type: boolean
        - name: health
          in: query
          description: Минимальное значение здоровья для фильтрации
          required: false
          schema:
            type: number
            minimum: 0
        - name: meleeWeapon
          in: query
          description: Фильтр по типу оружия (CHAIN_AXE, MANREAPER, POWER_BLADE)
          required: false
          schema:
              type: string
              enum:
                - CHAIN_AXE
                - MANREAPER
                - POWER_BLADE
        - name: chapterName
          in: query
          description: Фильтр по имени главы
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpaceMarine'
    post:
      summary: Создать новый SpaceMarine
      operationId: createSpaceMarine
      requestBody:
        description: Новый SpaceMarine
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '201':
          description: Успешное создание
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверные данные SpaceMarine
  /api/v1/space-marine-minimal:
    get:
      summary: Получить минимальный по coordinates SpaceMarine
      operationId: getSpaceMarineWithMinimumCoordinates
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
                
  /api/v1/space-marines/{health}: #loyal - это boolean и сделать по заданию не получится, поэтому я взял health
    get:
      summary: Получить количество SpaceMarine, значение health которых меньше заданного
      operationId: countSpaceMarinesWithHealthLessThan
      parameters:
        - name: health
          in: path
          description: Здоровье SpaceMarine
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarinesCount'
        '400':
          description: Неверный health
  /api/v1/space-marines/{id}:
    get:
      summary: Получить SpaceMarine по ID
      operationId: getSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверный id
  /space-marines/{id}/update:
    put:
      summary: Обновить SpaceMarine по ID
      operationId: updateSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      requestBody:
        description: Обновленный SpaceMarine
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '200':
          description: Успешное обновление
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверные данные SpaceMarine
        '422':
          description: Нарушение ограничений целостности
  /space-marines/{id}/delete:
    delete:
      summary: Удалить SpaceMarine по ID
      operationId: deleteSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешное удаление
        '400':
          description: Неверный id
  /api/v1/space-marines/{melee-weapon}:
    delete:
      summary: Удалить все SpaceMarines по meleeWeapon
      operationId: deleteSpaceMarinesByMeleeWeapon
      parameters:
        - name: melee-weapon
          in: path
          description: One of the melee weapons
          required: true
          schema:
            type: string
            enum:
            - CHAIN_AXE
            - MANREAPER
            - POWER_BLADE
      responses:
        '204':
          description: Успешное удаление
        '400':
          description: Неверный meleeWeapon
          
  /api/v1/starship/create/{id}/{name}:
    post:
      summary: Создать новый Starship
      operationId: createStarship
      parameters:
        - name: id
          in: path
          description: ID of starship
          required: true
          schema:
            type: integer
        - name: name
          in: path
          description: Name of the starship
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Успешное создание
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Starship'
        '400':
          description: Неверные данные Starship
  /api/v1/starship/{starship-id}/unload/{space-marine-id}:
    put:
      summary: Высадить десантника с корабля
      operationId: unloadMarineFromStarship
      parameters:
        - name: starship-id
          in: path
          description: ID of Starship
          required: true
          schema:
            type: integer
        - name: space-marine-id
          in: path
          description: ID of SpaceMarine
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Успешная высадка
        '400':
          description: Неверные данные Starship или SpaceMarine
        '401':
          description: Десантник не находится на этом корабле
components:
  schemas:
    SpaceMarine:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
        health:
          type: number
          minimum: 0
        loyal:
          type: boolean
        height:
          type: number
        meleeWeapon:
          type: string
          enum:
            - CHAIN_AXE
            - MANREAPER
            - POWER_BLADE
        chapter:
          $ref: '#/components/schemas/Chapter'
        starshipId:
          type: integer
    Coordinates:
      type: object
      properties:
        x:
          type: integer
          minimum: -246
        'y':
          type: integer
          minimum: -67
    Chapter:
      type: object
      properties:
        name:
          type: string
        parentLegion:
          type: string
        world:
          type: string
    SpaceMarinesCount:
      type: integer
    Starship:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
