openapi: 3.0.3
info:
  title: Управление коллекцией SpaceMarine
  description: API для управления коллекцией SpaceMarine
  version: 1.0.0
  contact:
    name: Артемкин Артем, Брудар Артем
  license:
    name: Лицензия
tags:
  - name: first-service-base
    description: Основной функционал первого сервиса
  - name: first-service-additional
    description: Дополнительный функционал первого сервиса
servers:
  - url: http://localhost:4532/api/v1
paths:
  /space-marines/search:
    post:
      tags:
        - first-service-base
      summary: Получить список SpaceMarine
      operationId: getSpaceMarines
      requestBody:
        description: Новый SpaceMarine
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SpaceMarineSearch'
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpaceMarine'
  /space-marines:
    post:
      tags:
        - first-service-base
      summary: Создать новый SpaceMarine
      operationId: createSpaceMarine
      requestBody:
        description: Новый SpaceMarine
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '201':
          description: Успешное создание
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверные данные SpaceMarine

  /space-marines/{id}:
    get:
      tags:
        - first-service-base
      summary: Получить SpaceMarine по ID
      operationId: getSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверный id
    
    put:
      tags:
        - first-service-base
      summary: Обновить SpaceMarine по ID
      operationId: updateSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      requestBody:
        description: Обновленный SpaceMarine
        required: true
        content:
          application/xml:
            schema:
              $ref: '#/components/schemas/SpaceMarine'
      responses:
        '200':
          description: Успешное обновление
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
        '400':
          description: Неверные данные SpaceMarine
    delete:
      tags:
        - first-service-base
      summary: Удалить SpaceMarine по ID
      operationId: deleteSpaceMarineById
      parameters:
        - name: id
          in: path
          description: ID SpaceMarine
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Успешное удаление
        '400':
          description: Неверный id
  /space-marines/{melee-weapon}:
    delete:
      tags:
        - first-service-additional
      summary: Удалить все SpaceMarines по meleeWeapon
      operationId: deleteSpaceMarinesByMeleeWeapon
      parameters:
        - name: melee-weapon
          in: path
          description: One of the melee weapons
          required: true
          schema:
            type: string
            enum:
            - CHAIN_AXE
            - MANREAPER
            - POWER_BLADE
      responses:
        '204':
          description: Успешное удаление
        '400':
          description: Неверный meleeWeapon
  /space-marine-minimal:
    get:
      tags:
        - first-service-additional
      summary: Получить минимальный по coordinates SpaceMarine
      operationId: getSpaceMarineWithMinimumCoordinates
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarine'
                
  /space-marines/{health}: #loyal - это boolean и сделать по заданию не получится, поэтому я взял health
    get:
      tags:
        - first-service-additional
      summary: Получить количество SpaceMarine, значение health которых меньше заданного
      operationId: countSpaceMarinesWithHealthLessThan
      parameters:
        - name: health
          in: path
          description: Здоровье SpaceMarine
          required: true
          schema:
            type: number
      responses:
        '200':
          description: Успешный ответ
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/SpaceMarinesCount'
        '400':
          description: Неверный health

components:
  schemas:
    SpaceMarineSearch:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
          enum:
            - ASC
            - DESC
        spaceMarine:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            coordinates:
              $ref: '#/components/schemas/Coordinates'
            creationDate:
              type: string
              format: date-time
            health:
              type: number
              minimum: 0
            loyal:
              type: boolean
            height:
              type: number
            meleeWeapon:
              type: string
              enum:
                - CHAIN_AXE
                - MANREAPER
                - POWER_BLADE
            chapter:
              $ref: '#/components/schemas/Chapter'
            starshipId:
              type: integer
    SpaceMarine:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        coordinates:
          $ref: '#/components/schemas/Coordinates'
        creationDate:
          type: string
          format: date-time
        health:
          type: number
          minimum: 0
        loyal:
          type: boolean
        height:
          type: number
        meleeWeapon:
          type: string
          enum:
            - CHAIN_AXE
            - MANREAPER
            - POWER_BLADE
        chapter:
          $ref: '#/components/schemas/Chapter'
        starshipId:
          type: integer
    Coordinates:
      type: object
      properties:
        x:
          type: integer
          minimum: -246
        'y':
          type: integer
          minimum: -67
    Chapter:
      type: object
      properties:
        name:
          type: string
        parentLegion:
          type: string
        world:
          type: string
    SpaceMarinesCount:
      type: integer
    Starship:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
