openapi: 3.0.3
info:
  title: Starship Service
  description: Starship service REST endpoints for SOA Lab_1
  version: 1.0.0
  contact:
    name: Артемкин Артем, Брудар Артем
  license:
    name: Лицензия
servers:
  - url: 'http://localhost:4532/api/v1'
paths:
  /starship/create/{id}/{name}:
    post:
      tags:
        - second-service-base
      summary: Создать новый Starship
      operationId: createStarship
      parameters:
        - name: id
          in: path
          description: ID Starship. Натуральное число
          required: true
          schema:
            type: integer
        - name: name
          in: path
          description: Имя starship. Строка
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Успешное создание
          content:
            application/xml:
              schema:
                $ref: './SpaceMarine.yaml#/components/schemas/Starship'
        '400':
          description: Неверные данные Starship
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StarshipWrongFields'
        '500':
          description: Сервер не готов обработать запрос
        '503':
          description: Сервис не готов обработать запрос
        default:
          description: Непредвиденная ошибка
          content:
            application/xml:
              schema:
                $ref: './SpaceMarine.yaml#/components/schemas/UnexpectedError'
  /starship/{starship-id}/unload/{space-marine-id}:
    put:
      tags:
        - second-service-base
      summary: Высадить десантника с корабля
      operationId: unloadMarineFromStarship
      parameters:
        - name: starship-id
          in: path
          description: ID Starship. Натуральное число
          required: true
          schema:
            type: integer
        - name: space-marine-id
          in: path
          description: ID SpaceMarine. Натуральное число
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Успешная высадка
        '400':
          description: Неверные данные Starship или SpaceMarine
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/LandWrongFields'
        '401':
          description: Десантник не находится на этом корабле
        '500':
          description: Ошибка сервера
        '503':
          description: Ошибка сервиса
        default:
          description: Непредвиденная ошибка
          content:
            application/xml:
              schema:
                $ref: './SpaceMarine.yaml#/components/schemas/UnexpectedError' 

components:
  schemas:
    StarshipWrongFields:
      type: object
      properties:
        wrongField:
          type: array
          items:
            type: string
    LandWrongFields:
      type: object
      properties:
        wrongField:
          type: string
          example: starship-ip
